openapi: 3.0.0
info:
  title: Battery Management API
  version: 1.0.0
  description: API for managing batteries and components

paths:
  /api/battery_components:
    get:
      summary: List battery components
      parameters:
        - in: query
          name: battery_id
          required: true
          description: ID of the battery to list components for
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BatteryComponent'
        '404':
          description: No battery components found for the provided battery ID

  /api/add_or_update_battery_component:
    post:
      summary: Add or update battery component
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatteryComponentInput'
      responses:
        '200':
          description: Successfully added or updated battery component
        '400':
          description: Invalid request body or parameters provided

  /api/delete_battery_component:
    post:
      summary: Delete battery component
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: ID of the battery component to delete
                  example: 123
      responses:
        '200':
          description: Battery component deleted successfully
        '400':
          description: Invalid request body or parameters provided
        '404':
          description: No battery component found for the provided ID

components:
  schemas:
    BatteryComponent:
      type: object
      properties:
        id:
          type: integer
        battery_id:
          type: integer
        component_id:
          type: integer
        qty:
          type: integer
        target_qty:
          type: integer
        status:
          type: string
      required:
        - id
        - battery_id
        - component_id
        - qty
        - target_qty
        - status

    BatteryComponentInput:
      type: object
      properties:
        id:
          type: integer
        battery_id:
          type: integer
        component_id:
          type: integer
        qty:
          type: integer
        target_qty:
          type: integer
        status:
          type: string
      required:
        - battery_id
        - component_id
        - qty
        - target_qty
        - status
